### ISSUE TITLE
simple changes of naming/ labeling etc.

### ISSUE THREAD

**Issue by Shintaro-Miyazaki** [commoningtoys/simple-common-ABM#1]
"happyness" to "happiness"
"collabirability" to "ability to collaborate"
"monthly hours" to "time units donated"
"protestant?" => "eager to spend all?"

**Comment by Yyyyaaaannnnoooo** [comment]
protestant oes nto equal to eager to spend all, rather in punishment for not spending all

**Comment by Yyyyaaaannnnoooo** [comment]
monthly hours => monthly engagement

**Comment by Shintaro-Miyazaki** [comment]
I thought "time units donated" is more precise but "monthly engagement" is also ok. 
"protestant?" => "sanctions?" yes means that there are sanctions for the agents, when they don't spend all the time units at the end of month?

**Comment by Yyyyaaaannnnoooo** [comment]
genau!
